app:
  port: 8888
  openApiPath: openapi.yml

  verticle:
    HelloWorldVerticle:
      enabled: true
      db:
        url: jdbc:h2:./.h2/helloworld
        username: sa
        password: sa
      handler:
        greeting:
          enabled: true
          eventType: GREET
          opts:
            journalUrl: test123
    TraceLogVerticle:
      enabled: true
      db:
        url: jdbc:h2:./.h2/tracelog
        username: sa
        password: sa
      handler:
        saveLog:
          enabled: true
          eventType: SAVE_LOG
