app:
  port: 8888
  openApiPath: openapi.yml

  verticle:
    HelloWorldVerticle:
      enabled: true
      db:
        url: jdbc:h2:./.h2/helloworld;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090
        username: sa
        password: sa
      handler:
        greeting:
          enabled: true
