openapi: 3.0.3

info:
  title: Anas Juwaidi's SuperApp - OpenAPI 3.0
  description: |
    **Anas Juwaidi's SuperApp**
  termsOfService: http://swagger.io/terms/
  contact:
    email: anas.didi95@tutamail.com
  version: 0.1.0

servers:
  - url: http://localhost:8888
    description: dev

tags:
  - name: auth
    description: Authentication
  - name: hello-world
    description: Hello World

paths:
  /hello-world/v1/greet:
    get:
      tags:
        - hello-world
      description: Greet
      summary: Greet
      operationId: greet
      security:
        - bearerAuth: []
      parameters:
        - name: lang
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloWorldGreetResDto"
  /auth/v1/login:
    post:
      tags:
        - auth
      summary: Login
      description: Login
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthLoginReqDto"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthLoginResDto"
  /auth/v1/user:
    post:
      tags:
        - auth
      summary: Add User
      description: Add User
      operationId: addUser
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthAddUserReqDto"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthAddUserResDto"

components:
  schemas:
    # HelloWorldGreetReqDto:
    #   type: object
    HelloWorldGreetResDto:
      type: object
      properties:
        lang:
          type: string
          nullable: false
        value:
          type: string
          nullable: false
    AuthLoginReqDto:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          nullable: false
        password:
          type: string
          nullable: false
    AuthLoginResDto:
      type: object
      properties:
        accessToken:
          type: string
          nullable: false
    AuthAddUserReqDto:
      type: object
      required:
        - username
        - password
        - channelId
        - roleId
      properties:
        username:
          type: string
          nullable: false
        password:
          type: string
          nullable: false
        channelId:
          type: string
          nullable: false
          example: DEV
        roleId:
          type: string
          nullable: false
          example: abbacd28-53e8-4457-a8a8-54626997efc0
    AuthAddUserResDto:
      type: object
      properties:
        traceId:
          type: string
          nullable: false

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
