openapi: 3.0.3

info:
  title: Anas Juwaidi's SuperApp - OpenAPI 3.0
  description: |-
    **Anas Juwaidi's SuperApp**
  termsOfService: http://swagger.io/terms/
  contact:
    email: anas.didi95@tutomail.com
  version: 0.1.0

servers:
  - url: http://localhost:8888
    description: dev

tags:
  - name: hello-world
    description: Hello World

paths:
  /hello-world/v1/greet:
    get:
      tags:
        - hello-world
      description: Greeting
      summary: Greeting
      operationId: greeting
      parameters:
        - name: lang
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK

components:
  schemas:
    HelloWorld:
      type: object
      properties:
        lang:
          type: string
        value:
          type: string
